[tool.black]
line-length = 120
target-version = ['py38']
include = '\.py$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | \venv*
  | _build
  | build
  | dist
  | lib
  | include
  | bin
)/
'''