service: take-home-assessment

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  get_all_services:
    handler: src.exampleco.exampleco.api.services.get_all_services
    events:
      - httpApi:
          path: /services
          method: get
  get_service:
    handler: src.exampleco.exampleco.api.services.get_service
    events:
      - httpApi:
          path: /services/{pk}
          method: get
  get_all_orders:
    handler: src.exampleco.exampleco.api.orders.get_all_orders
    events:
      - httpApi:
          path: /orders
          method: get
  get_order:
    handler: src.exampleco.exampleco.api.orders.get_order
    events:
      - httpApi:
          path: /orders/{pk}
          method: get
